baseURL: "https://devrel-unconference.com"
languageCode: en-us
title: "DevRel Unconference 2024"
theme: piko
paginate: "9"
Copyright: "DevRel Unconference"
googleAnalytics: # Enter Google Analytics ie. UA-012345678-9
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
outputs:
  home:
  - HTML
  - RSS
  - JSON
minify:
  disableCSS: false
  disableHTML: false
  disableJS: false
  disableJSON: false
  disableSVG: false
  disableXML: false
  minifyOutput: true
  tdewolff:
    html:
      keepWhitespace: false

params:
  analytics:
    google:
      SiteVerificationTag: # Google Site Verification
    bing:
      SiteVerificationTag: # Bing Site Verification
  env: development

  description: "Developer Relations Unconference 2024: TBA"
  label:
    darkNavIcon: "images/stylized-25px.svg"
    lightNavIcon: "images/stylized-25px.svg"
  ShowShareButtons: true
  ShowCodeCopyButtons: true
  ShowRelated: true
  CookieNotice: We use cookies to improve your experience on our site and to show
    you relevant advertising.
  CookieLink: /legal/privacy/#cookies-and-web-beacons

  assets:
    disableFingerprinting: true
    favicon: "images/stylized-25px.svg"
    favicon16x16: "images/stylized-25px.svg"
    favicon32x32: "images/stylized-25px.svg"
    apple_touch_icon: "images/stylized-25px.svg"
    safari_pinned_tab: "images/stylized-25px.svg"
  ShowReadingTime: true
  ShowBreadCrumbs: true

  homepage:
    # Hero section
    disableHeroSection: false
    heroUpperText: "DevRel Unconference 2024"
    hereText: "DevRel Unconference"
    heroTitle: "DevRel Unconference 2024"
    heroDescription: "A conference for developer relations professionals where conversation and moving forward is the point."
    heroCTAPrimaryText: About
    heroCTAPrimaryUrl: "#about"
    heroCTASecondaryText: Contact Organizers
    heroCTASecondaryUrl: "/contact/"
    heroBackgroundImage: "images/stem-list-EVgsAbL51Rk-unsplash-min.jpg" # https://unsplash.com/photos/EVgsAbL51Rk
    # Blog Section
    disableBlogSection: false
    blogTitle: Latest News
    blogDescription: Find out the latest news on the unconference
    seeMoreText: More
    # About Section    
    disableAboutSection: false
    aboutTitle: About Us
    aboutDescription: About DevRel Unconference and the organizers
    aboutImgUrl: "images/sam-moghadam-khamseh-IfxXudgTs8Q-unsplash.jpg" # https://unsplash.com/photos/IfxXudgTs8Q
    aboutContent: "We are some peeps who care about DevRel and want to make a conference that is different from the rest."
    # Speakers Section
    disableSpeakersSection: false
    speakersTitle: Speakers
    speakersDescription: Say hello to this year's speakers
    speakers:
    - imageUrl: images/free-avatar-image.png # https://www.seekpng.com/ipng/u2w7i1y3y3i1r5i1_this-free-clipart-png-design-of-blank-avatar/
      alt: # image alt for better SEO
      description: Speaker One
      websiteUrl: #
    - imageUrl: images/free-avatar-image.png # https://www.seekpng.com/ipng/u2w7i1y3y3i1r5i1_this-free-clipart-png-design-of-blank-avatar/
      alt: # image alt for better SEO
      description: Speaker Two
      websiteUrl: #
    - imageUrl: images/free-avatar-image.png # https://www.seekpng.com/ipng/u2w7i1y3y3i1r5i1_this-free-clipart-png-design-of-blank-avatar/
      alt: # image alt for better SEO
      description: Speaker Three
      websiteUrl: #
    # Sponsors Section
    disableSponsorsSection: false
    sponsorsTitle: Sponsors
    sponsorsDescription: Thank you to our sponsors
    sponsors:
    - imageUrl: /uploads/sponsor-1.webp
      alt: # image alt for better SEO
      description: Sponsor One.
      websiteUrl: #
    - imageUrl: /uploads/sponsor-2.webp
      alt: # image alt for better SEO
      description: Sponsor Two.
      websiteUrl: #
  plugins:
    css:
    - link: plugins/css/pico.min.css
    js:
    - link: plugins/js/feather.min.js

menus:
  main: # Main Menu
  - name: Blog
    title: Blog
    pre: pen-tool
    url: "/blog"
    weight: "20"
  # - name: Search
  #   title: Search
  #   pre: search
  #   url: "/search"
  #   weight: "30"
  - name: Speakers
    title: Speakers
    pre: users
    url: "#speakers"
    weight: "30"
  - name: Sponsors
    title: Sponsors
    pre: package
    url: "#sponsors"
    weight: "40"
  - name: Agenda
    title: Agenda
    pre: calendar
    url: "#agenda"
    weight: "50"
  - name: Contact
    title: Contact
    pre: mail
    url: "/contact"
    weight: "60"
  - name: Twitter
    title: 
    pre: twitter
    url: https://twitter.com/DevRel_Unconf
    weight: "70"
  - name: Github
    title: 
    pre: github
    url: https://github.com/devrel-unconference/devrel-unconf-website
    weight: "80"
  # search: # Search page's quick links
  # - name: Categories
  #   title: Categories
  #   url: "/categories"
  #   weight: "10"
  # - name: Archives
  #   title: Archives
  #   url: "/archives"
  #   weight: "20"
  # - name: Tags
  #   title: Tags
  #   url: "/tags"
  #   weight: "30"
